### ISSUE TITLE
Mipmap Support

### ISSUE THREAD

**Issue by Kyusetzu** [captainsouthbird/CGFXModel#1]
So, I have no idea if this project is still alive, but adding mipmap support would be gladly appreciated.
(For up to 3 levels would be enough tho)
![Mipmap error](https://i.imgur.com/kS7kU5M.png)

**Comment by captainsouthbird** [comment]
I won't be working on this anymore as I've simply lost interest... it only needed to be good enough to support my trivial YouTube uses. By and large I've moved on, though.
